import express from 'express';
import Order from '../models/Order.js';
import { protect } from '../middleware/auth.js';
import {
  sendOrderStatusUpdate,
  sendPaymentAlertToAdmin,
  sendDeliveryFeeUpdate
} from '../utils/emailTemplates.js';
import createNotification from '../utils/createNotification.js';
// ❌ removed: import getNextSequence from '../utils/getNextSequence.js';

const router = express.Router();

// ─── PUBLIC TRACKING ENDPOINT (no auth) ───────────────
router.get('/track', async (req, res) => {
  try {
    const { order_id, email } = req.query;
    if (!order_id || !email) {
      return res.status(400).json({ message: 'Order ID and email are required' });
    }
    const order = await Order.findOne({
      order_id: order_id.toUpperCase(),
      customerEmail: email.toLowerCase().trim(),
      isDeleted: false,
    }).select(
      'order_id customerName customerEmail status totalAmount items createdAt delivery_fee order_type statusHistory'
    );

    if (!order) return res.status(404).json({ message: 'Order not found' });

    const statusHistory = (order.statusHistory || []).map(entry => ({
      status: entry.status,
      date: entry.timestamp,
    }));

    res.json({
      order_id: order.order_id,
      customerName: order.customerName,
      totalAmount: order.totalAmount,
      delivery_fee: order.delivery_fee,
      order_type: order.order_type,
      status: order.status,
      items: order.items,
      statusHistory,
      createdAt: order.createdAt,
    });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// ─── CREATE ORDER (public) ───────────────────────────
router.post('/', async (req, res) => {
  try {
    // ✅ No longer manually create order_id – the pre‑save hook in Order.js does it
    const orderData = {
      ...req.body,
      status: 'Pending',
      payment_status: 'unpaid',
      // order_id is NOT set here – will be auto‑generated by the model
    };
    delete orderData._id; // safety

    const order = await Order.create(orderData);

    createNotification({
      type: 'new_order',
      message: `New order #${order.order_id} from ${order.customerName || 'Customer'}`,
      relatedId: order._id,
    });

    res.status(201).json(order);
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
});

// ─── MARK AS PAID (public – called after Paystack) ────
router.patch('/:id/mark-paid', async (req, res) => {
  try {
    const order = await Order.findById(req.params.id);
    if (!order) return res.status(404).json({ message: 'Order not found' });
    order.payment_status = 'paid';
    order.status = 'Paid';
    await order.save();

    // Admin alert only – no customer email for payment confirmation
    sendPaymentAlertToAdmin(order).catch(err => console.error(err));

    createNotification({
      type: 'payment_receipt',
      message: `Payment received for order #${order.order_id}`,
      relatedId: order._id,
    });

    res.json(order);
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
});

// ─── ADMIN: GET ALL (exclude deleted by default, ?deleted=true to include) ──
router.get('/', protect, async (req, res) => {
  try {
    const includeDeleted = req.query.deleted === 'true';
    const filter = includeDeleted ? {} : { isDeleted: false };
    const orders = await Order.find(filter).sort({ createdAt: -1 });
    res.json(orders);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// ─── ADMIN: GET SINGLE ──────────────────────────────
router.get('/:id', protect, async (req, res) => {
  try {
    const order = await Order.findById(req.params.id);
    if (!order) return res.status(404).json({ message: 'Not found' });
    res.json(order);
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
});

// ─── ADMIN: UPDATE STATUS ───────────────────────────
router.patch('/:id/status', protect, async (req, res) => {
  try {
    const order = await Order.findById(req.params.id);
    if (!order) return res.status(404).json({ message: 'Order not found' });
    if (order.status === 'Delivered') {
      return res.status(400).json({ message: 'Delivered orders cannot be changed' });
    }

    const newStatus = req.body.status;
    const currentStatus = order.status;

    const allowedTransitions = {
      'Pending': [],
      'Paid': ['Processing'],
      'Processing': ['Out for Delivery'],
      'Out for Delivery': ['Delivered'],
      'Delivered': []
    };

    if (!allowedTransitions[currentStatus]?.includes(newStatus)) {
      return res.status(400).json({ message: `Cannot move from ${currentStatus} to ${newStatus}` });
    }

    order.statusHistory = order.statusHistory || [];
    order.statusHistory.push({
      status: newStatus,
      changedBy: req.user.email || req.user.id,
      previousStatus: currentStatus,
      timestamp: new Date(),
    });

    order.status = newStatus;
    await order.save();

    // Customer email only for these statuses
    if (['Processing', 'Out for Delivery', 'Delivered'].includes(newStatus)) {
      sendOrderStatusUpdate(order).catch(err => console.error(err));
    }

    createNotification({
      type: 'order_status',
      message: `Order #${order.order_id} changed to ${newStatus}`,
      relatedId: order._id,
    });

    res.json(order);
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
});

// ─── ADMIN: UPDATE DELIVERY FEE ─────────────────────
router.patch('/:id/delivery-fee', protect, async (req, res) => {
  try {
    const order = await Order.findById(req.params.id);
    if (!order) return res.status(404).json({ message: 'Not found' });
    order.delivery_fee = req.body.delivery_fee;
    await order.save();

    sendDeliveryFeeUpdate(order, order.delivery_fee).catch(err =>
      console.error('Delivery fee email error:', err)
    );

    res.json(order);
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
});

// ─── ADMIN: SOFT DELETE ─────────────────────────────
router.delete('/:id', protect, async (req, res) => {
  try {
    const order = await Order.findById(req.params.id);
    if (!order) return res.status(404).json({ message: 'Not found' });
    order.isDeleted = true;
    order.deletedAt = new Date();
    await order.save();
    res.json({ message: 'Order moved to trash' });
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
});

// ─── ADMIN: RESTORE ─────────────────────────────────
router.patch('/:id/restore', protect, async (req, res) => {
  try {
    const order = await Order.findById(req.params.id);
    if (!order) return res.status(404).json({ message: 'Not found' });
    order.isDeleted = false;
    order.deletedAt = null;
    await order.save();
    res.json(order);
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
});

// ─── ADMIN: PERMANENT DELETE ────────────────────────
router.delete('/:id/permanent', protect, async (req, res) => {
  try {
    await Order.findByIdAndDelete(req.params.id);
    res.json({ message: 'Permanently deleted' });
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
});

export default router;